from playwright.sync_api import expect
import os
os.environ['REDIS_TIMEOUT'] = '1'

def test_delete_profile_success(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    text = page.locator("p")
    expect(text).to_have_text("You have entered a dangerous area. Deleting your profile is an unrecoverable operation. Are you sure you want to continue?")
    page.click("text='Continue'")
    text = page.locator("label")
    expect(text).to_have_text("Enter your password:")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    text = page.locator("label")
    expect(text).to_have_text("Enter your year of birth:")
    page.fill("#birth_year", "1995")
    page.click("text='Continue'")
    text = page.locator("p")
    expect(text).to_have_text("Type the following to confirm:")
    text = page.locator("label")
    expect(text).to_have_text("I, son_of_john, confirm that I want to delete my profile.")
    page.fill("#user_name", "I, son_of_john, confirm that I want to delete my profile.")
    page.click("text='Commit to it!'")
    text = page.locator("h1")
    expect(text).to_have_text("Account Deleted")
    text = page.locator("p")
    expect(text).to_have_text("Your account and all your data associated with it was successfully deleted.")
    text = page.locator("h2")
    expect(text).to_have_text("Goodbye!")
    page.click("text='Chitter Homepage'")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    error = page.locator(".log_in_error")
    expect(error).to_have_text("Something doesn't match there!")

def test_delete_profile_cancel_at_stage_1(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Cancel'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_cancel_at_stage_2(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Cancel'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_incorrect_password(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "never00!")
    page.click("text='Continue'")
    error = page.locator(".cp_error")
    expect(error).to_have_text("Password did not match!")

def test_delete_profile_cancel_at_stage_3(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.fill("#birth_year", "1995")
    page.click("text='Cancel'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_incorrect_year_of_birth(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.fill("#birth_year", "1996")
    page.click("text='Continue'")
    error = page.locator(".cp_error")
    expect(error).to_have_text("Year of birth did not match!")

def test_delete_profile_letter_in_year_of_birth(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.fill("#birth_year", "199o")
    page.click("text='Continue'")
    error = page.locator(".cp_error")
    expect(error).to_have_text("Year of birth did not match!")

def test_delete_profile_cancel_at_stage_4(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.fill("#birth_year", "1995")
    page.click("text='Continue'")
    page.fill("#user_name", "I, son_of_john, confirm that I want to delete my profile.")
    page.click("text='Cancel!'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_incorrect_final_confirmation(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.fill("#birth_year", "1995")
    page.click("text='Continue'")
    page.fill("#user_name", "I, son_of_john, confirm that I want to delete my profile")
    page.click("text='Commit to it!'")
    error = page.locator(".cp_error")
    expect(error).to_have_text("Your final confirmation did not match!")

def test_delete_profile_timeout_stage_1(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.wait_for_timeout(1000)
    page.click("text='Continue'")
    text = page.locator("h1")
    expect(text).to_have_text("Time Exceeded")
    text = page.locator("p")
    expect(text).to_have_text("You took too long. Please go back and start again.")
    page.click("text='Back to Profile'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_timeout_stage_2(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.wait_for_timeout(1000)
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    text = page.locator("h1")
    expect(text).to_have_text("Time Exceeded")
    text = page.locator("p")
    expect(text).to_have_text("You took too long. Please go back and start again.")
    page.click("text='Back to Profile'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_timeout_stage_3(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.wait_for_timeout(1000)
    page.fill("#birth_year", "1995")
    page.click("text='Continue'")
    text = page.locator("h1")
    expect(text).to_have_text("Time Exceeded")
    text = page.locator("p")
    expect(text).to_have_text("You took too long. Please go back and start again.")
    page.click("text='Back to Profile'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")

def test_delete_profile_timeout_stage_4(page, test_web_address, db_connection):
    db_connection.seed("seeds/chitter_data.sql")
    page.goto(f"http://{test_web_address}")
    page.fill(".user-name-tag", "son_of_john")
    page.fill(".password-tag", "Never00!")
    page.click("text='Log in'")
    page.click("text='View Profile'")
    page.click("text='Delete Profile'")
    page.click("text='Continue'")
    page.fill("#password", "Never00!")
    page.click("text='Continue'")
    page.fill("#birth_year", "1995")
    page.click("text='Continue'")
    page.wait_for_timeout(1000)
    page.fill("#user_name", "I, son_of_john, confirm that I want to delete my profile.")
    page.click("text='Commit to it!'")
    text = page.locator("h1")
    expect(text).to_have_text("Time Exceeded")
    text = page.locator("p")
    expect(text).to_have_text("You took too long. Please go back and start again.")
    page.click("text='Back to Profile'")
    all_lines = page.locator(".top-bar-box-user")
    expect(all_lines).to_have_text("View Profile\nLog out\nson_of_john's Profile")